"use client";

import { useCallback } from "react";
import { useLanguage } from "@/features/language/language-context";

const clinicTextBn: Record<string, string> = {
  "AI drafts safe Bangla-English answers for clinician review":
    "ক্লিনিশিয়ান রিভিউয়ের জন্য AI নিরাপদ বাংলা-ইংরেজি উত্তর ড্রাফট করে",
  "AI reviews incoming patient replies after follow-up":
    "ফলো-আপের পর রোগীর আসা উত্তর AI রিভিউ করে",
  "Answer Patient Question": "রোগীর প্রশ্নের উত্তর দিন",
  "Answering...": "উত্তর তৈরি হচ্ছে...",
  "Bangla answer": "বাংলা উত্তর",
  "Bangla response": "বাংলা উত্তর",
  "Capture Bangla-English intake at reception.":
    "রিসেপশনে বাংলা-ইংরেজি ইনটেক নিন।",
  "Case summary": "কেস সারাংশ",
  "Chief complaint": "প্রধান অভিযোগ",
  "Clinic flow": "ক্লিনিক ফ্লো",
  "Clinic tracks follow-up and anonymized trends.":
    "ক্লিনিক ফলো-আপ ও অ্যানোনিমাইজড ট্রেন্ড ট্র্যাক করে।",
  Close: "বন্ধ করুন",
  "Clinician review": "ক্লিনিশিয়ান রিভিউ",
  "Clinician reviews and approves the note.":
    "ক্লিনিশিয়ান নোট রিভিউ ও অনুমোদন করেন।",
  "Command Copilot": "কমান্ড কোপাইলট",
  Concerning: "উদ্বেগজনক",
  Copy: "কপি",
  "Current case": "বর্তমান কেস",
  "Doctor Console": "ডাক্তার কনসোল",
  "Draft support only, clinician reviewed": "শুধু ড্রাফট সহায়তা, ক্লিনিশিয়ান রিভিউড",
  "English answer": "ইংরেজি উত্তর",
  "English response": "ইংরেজি উত্তর",
  "Load a scenario to start": "শুরু করতে একটি সিনারিও লোড করুন",
  "Missing Questions": "মিসিং প্রশ্ন",
  "Missing questions found": "মিসিং প্রশ্ন পাওয়া",
  "Paste a patient question, or ask the command box to answer it.":
    "রোগীর প্রশ্ন পেস্ট করুন, অথবা কমান্ড বক্সকে উত্তর দিতে বলুন।",
  "Paste a patient reply, or ask the command box to triage it.":
    "রোগীর উত্তর পেস্ট করুন, অথবা কমান্ড বক্সকে ট্রায়াজ করতে বলুন।",
  "Paste the patient or family question first.":
    "আগে রোগী বা পরিবারের প্রশ্ন পেস্ট করুন।",
  "Paste the patient's reply before triage.": "ট্রায়াজের আগে রোগীর উত্তর পেস্ট করুন।",
  "Patient Question": "রোগীর প্রশ্ন",
  "Patient follow-up reply": "রোগীর ফলো-আপ উত্তর",
  "Patient or family question": "রোগী বা পরিবারের প্রশ্ন",
  "Patient leaves with a plain Bangla handout.":
    "রোগী সহজ বাংলা হ্যান্ডআউট নিয়ে যায়।",
  "Patient question answer failed.": "রোগীর প্রশ্নের উত্তর তৈরি ব্যর্থ হয়েছে।",
  "Red flags caught": "রেড ফ্ল্যাগ ধরা",
  "Red flags": "রেড ফ্ল্যাগ",
  Reassuring: "আশ্বস্তকর",
  "Reply Triage": "রিপ্লাই ট্রায়াজ",
  "Reply triage failed.": "রিপ্লাই ট্রায়াজ ব্যর্থ হয়েছে।",
  "Safety Red Flags": "সেফটি রেড ফ্ল্যাগ",
  "Safety reminders": "সেফটি রিমাইন্ডার",
  "Save edits": "এডিট সেভ করুন",
  "Seeded demo cases": "সিডেড ডেমো কেস",
  "SOAP note": "SOAP নোট",
  "Staff actions": "স্টাফ অ্যাকশন",
  "Suggested commands": "সাজেস্টেড কমান্ড",
  Shortcuts: "শর্টকাট",
  "Teach-back": "টিচ-ব্যাক",
  "Triage Patient Reply": "রোগীর উত্তর ট্রায়াজ করুন",
  "Triaging...": "ট্রায়াজ হচ্ছে...",
  "Use the command copilot or guided workflow controls to drive the presentation.":
    "প্রেজেন্টেশন চালাতে কমান্ড কোপাইলট বা গাইডেড ওয়ার্কফ্লো কন্ট্রোল ব্যবহার করুন।",
  "AI finds missing questions and urgent red flags.":
    "AI মিসিং প্রশ্ন ও জরুরি রেড ফ্ল্যাগ খুঁজে।",
  "AI final packet, follow-up closure, and audit notes":
    "AI ফাইনাল প্যাকেট, ফলো-আপ ক্লোজার ও অডিট নোট",
  "AI parses lab, prescription, and OCR text into case facts":
    "AI ল্যাব, প্রেসক্রিপশন ও OCR টেক্সট থেকে কেস তথ্য বের করে",
  Admin: "অ্যাডমিন",
  "Admin workspace": "অ্যাডমিন ওয়ার্কস্পেস",
  "Apply addendum to intake": "ইনটেকে অ্যাডেনডাম যোগ করুন",
  "Attach or paste report text, then ask the command box to extract it.":
    "রিপোর্ট টেক্সট অ্যাটাচ বা পেস্ট করুন, তারপর কমান্ড বক্সকে এক্সট্র্যাক্ট করতে বলুন।",
  "Audit notes": "অডিট নোট",
  "Before patient leaves": "রোগী যাওয়ার আগে",
  Builder: "বিল্ডার",
  "Builder workspace": "বিল্ডার ওয়ার্কস্পেস",
  Case: "কেস",
  "Case workspace": "কেস ওয়ার্কস্পেস",
  "Chat, tools, runs, approvals, memory, MCP":
    "চ্যাট, টুল, রান, অ্যাপ্রুভাল, মেমরি, MCP",
  "Capture intake": "ইনটেক নিন",
  "Clean intake note with AI": "AI দিয়ে ইনটেক নোট পরিষ্কার করুন",
  "Clean intake with AI": "AI দিয়ে ইনটেক পরিষ্কার করুন",
  "Load demo scenario": "ডেমো সিনারিও লোড করুন",
  "Set patient sex to": "রোগীর লিঙ্গ সেট করুন",
  "Start Bangla voice intake": "বাংলা ভয়েস ইনটেক শুরু করুন",
  "Voice intake is listening": "ভয়েস ইনটেক শুনছে",
  female: "নারী",
  male: "পুরুষ",
  other: "অন্যান্য",
  "Fever desk": "জ্বর ডেস্ক",
  "Fast Bangla fever triage": "দ্রুত বাংলা জ্বর ট্রায়াজ",
  "Cardiac risk": "কার্ডিয়াক ঝুঁকি",
  "High-priority red-flag escalation": "উচ্চ অগ্রাধিকার রেড-ফ্ল্যাগ এসক্যালেশন",
  "Child hydration": "শিশু হাইড্রেশন",
  "Parent-friendly Bangla handout": "অভিভাবকবান্ধব বাংলা হ্যান্ডআউট",
  "Dengue watch": "ডেঙ্গু ওয়াচ",
  "Local outbreak-aware missing questions": "লোকাল আউটব্রেক-অওয়ার মিসিং প্রশ্ন",
  "Pregnancy fever": "প্রেগন্যান্সি জ্বর",
  "Sensitive escalation with safety language": "সেফটি ভাষাসহ সংবেদনশীল এসক্যালেশন",
  "Diabetes wound": "ডায়াবেটিস ক্ষত",
  "Chronic-care follow-up workflow": "ক্রনিক-কেয়ার ফলো-আপ ওয়ার্কফ্লো",
  "Agent command": "এজেন্ট কমান্ড",
  "Agentic clinic operating layer": "এজেন্টিক ক্লিনিক অপারেটিং লেয়ার",
  "AI agent workspace": "AI এজেন্ট ওয়ার্কস্পেস",
  "Run agent": "এজেন্ট চালান",
  "Run agent tool": "এজেন্ট টুল চালান",
  "Run queued agent task": "কিউড এজেন্ট টাস্ক চালান",
  tool: "টুল",
  "Close help drawer": "হেল্প ড্রয়ার বন্ধ করুন",
  "Close Visit Safely": "নিরাপদে ভিজিট ক্লোজ করুন",
  "Close workspace navigation": "ওয়ার্কস্পেস নেভিগেশন বন্ধ করুন",
  Closing: "ক্লোজ হচ্ছে",
  "Closing...": "ক্লোজ হচ্ছে...",
  "Copilot output is draft support only.": "কোপাইলট আউটপুট শুধু ড্রাফট সহায়তা।",
  "Copilot workspace": "কোপাইলট ওয়ার্কস্পেস",
  Copilot: "কোপাইলট",
  "Paste Bangla, English, or mixed notes.": "বাংলা, ইংরেজি বা মিশ্র নোট পেস্ট করুন।",
  "Document extraction failed.": "ডকুমেন্ট এক্সট্র্যাকশন ব্যর্থ হয়েছে।",
  "Document Extractor": "ডকুমেন্ট এক্সট্র্যাক্টর",
  "Extract Document Text": "ডকুমেন্ট টেক্সট এক্সট্র্যাক্ট করুন",
  Extracting: "এক্সট্র্যাক্ট হচ্ছে",
  "Extracting...": "এক্সট্র্যাক্ট হচ্ছে...",
  "Follow-up closure": "ফলো-আপ ক্লোজার",
  "Generate draft": "ড্রাফট তৈরি করুন",
  "AI extracts structure and safety gaps.": "AI কাঠামো ও সেফটি গ্যাপ বের করে।",
  "Generate or select a case before closing the visit.":
    "ভিজিট ক্লোজ করার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  Help: "হেল্প",
  "Help and tools": "হেল্প ও টুল",
  "MCP call failed.": "MCP কল ব্যর্থ হয়েছে।",
  "One patient, intake, safety, draft, packet":
    "এক রোগী, ইনটেক, সেফটি, ড্রাফট, প্যাকেট",
  "Open public docs and tool catalog": "পাবলিক ডকস ও টুল ক্যাটালগ খুলুন",
  "Open workspace navigation": "ওয়ার্কস্পেস নেভিগেশন খুলুন",
  "Operations workspace": "অপারেশনস ওয়ার্কস্পেস",
  "Paste or attach lab, prescription, or OCR text first.":
    "আগে ল্যাব, প্রেসক্রিপশন বা OCR টেক্সট পেস্ট বা অ্যাটাচ করুন।",
  "Prepare final staff steps, patient instructions, print packet, and audit notes before the visit leaves the workflow.":
    "ভিজিট ওয়ার্কফ্লো ছাড়ার আগে ফাইনাল স্টাফ স্টেপ, রোগীর নির্দেশনা, প্রিন্ট প্যাকেট ও অডিট নোট প্রস্তুত করুন।",
  "Primary mobile workspace": "প্রাইমারি মোবাইল ওয়ার্কস্পেস",
  "Print packet": "প্রিন্ট প্যাকেট",
  Queue: "কিউ",
  "Queue workspace": "কিউ ওয়ার্কস্পেস",
  "Review handout": "হ্যান্ডআউট রিভিউ করুন",
  "Doctor approves patient instructions.": "ডাক্তার রোগীর নির্দেশনা অনুমোদন করেন।",
  doctor: "ডাক্তার",
  nurse: "নার্স",
  receptionist: "রিসেপশনিস্ট",
  "Settings, roles, MCP, audit, readiness": "সেটিংস, রোল, MCP, অডিট, রেডিনেস",
  "Shift brief, analytics, follow-up, offline sync":
    "শিফট ব্রিফ, অ্যানালিটিক্স, ফলো-আপ, অফলাইন সিঙ্ক",
  "Shortcuts, safety rules, and tool reference live here so the workspace can stay calm.":
    "শর্টকাট, সেফটি রুল ও টুল রেফারেন্স এখানে থাকে, যাতে ওয়ার্কস্পেস শান্ত থাকে।",
  "Sign out": "সাইন আউট",
  "Staff closeout": "স্টাফ ক্লোজআউট",
  "Use Case for patient work; use Copilot for questions and agent actions.":
    "রোগীর কাজের জন্য Case ব্যবহার করুন; প্রশ্ন ও এজেন্ট অ্যাকশনের জন্য Copilot ব্যবহার করুন।",
  "Useful Copilot asks": "ব্যবহারযোগ্য কোপাইলট প্রশ্ন",
  "Visit Closeout": "ভিজিট ক্লোজআউট",
  "Visit closeout failed.": "ভিজিট ক্লোজআউট ব্যর্থ হয়েছে।",
  "Vitals, allergies, escalation, return warnings, and clinician approval stay visible before print.":
    "প্রিন্টের আগে ভাইটাল, অ্যালার্জি, এসক্যালেশন, রিটার্ন ওয়ার্নিং ও ক্লিনিশিয়ান অনুমোদন দৃশ্যমান থাকে।",
  "Waiting room, red flags, owners, and follow-ups":
    "ওয়েটিং রুম, রেড ফ্ল্যাগ, মালিকানা ও ফলো-আপ",
  "Workflow canvas, protocols, simulation, templates":
    "ওয়ার্কফ্লো ক্যানভাস, প্রোটোকল, সিমুলেশন, টেমপ্লেট",
  Workspace: "ওয়ার্কস্পেস",
  workspace: "ওয়ার্কস্পেস",
  "Cmd/Ctrl+G generates a draft": "Cmd/Ctrl+G ড্রাফট তৈরি করে",
  "Cmd/Ctrl+K opens Copilot": "Cmd/Ctrl+K কোপাইলট খোলে",
  "Cmd/Ctrl+P opens presentation mode": "Cmd/Ctrl+P প্রেজেন্টেশন মোড খোলে",
  "Esc closes presentation mode": "Esc প্রেজেন্টেশন মোড বন্ধ করে",
  "Explain this in simple Bangla.": "এটা সহজ বাংলায় ব্যাখ্যা করুন।",
  "Is this safe to print?": "এটা প্রিন্ট করা নিরাপদ কি?",
  "Prepare follow-up ownership.": "ফলো-আপ মালিকানা প্রস্তুত করুন।",
  "What should I do next?": "এরপর কী করা উচিত?",
  bn: "বাংলা",
  en: "ইংরেজি",
  h: "ঘণ্টা",
  m: "মিনিট",
  mixed: "মিশ্র",
  "AI checks blockers before clinician signoff":
    "ক্লিনিশিয়ান সাইনঅফের আগে AI ব্লকার চেক করে",
  "AI task split for receptionist, nurse, doctor, and follow-up desk":
    "রিসেপশনিস্ট, নার্স, ডাক্তার ও ফলো-আপ ডেস্কের জন্য AI টাস্ক ভাগ করে",
  "Approval Guard": "অ্যাপ্রুভাল গার্ড",
  "Approval readiness check failed.": "অ্যাপ্রুভাল রেডিনেস চেক ব্যর্থ হয়েছে।",
  "Accessibility notes": "অ্যাক্সেসিবিলিটি নোট",
  "AI callback timing, reminders, and closure rules":
    "AI কলব্যাক টাইমিং, রিমাইন্ডার ও ক্লোজার রুল",
  "AI turns the selected case into actions and commands":
    "AI সিলেক্ট করা কেসকে অ্যাকশন ও কমান্ডে বদলায়",
  "Ask for a nurse handoff or team task list from the command box.":
    "কমান্ড বক্স থেকে নার্স হ্যান্ডঅফ বা টিম টাস্ক লিস্ট চাইুন।",
  "Ask why a case is risky, or run the explanation here.":
    "কেসটি কেন ঝুঁকিপূর্ণ তা জিজ্ঞেস করুন, অথবা এখানে ব্যাখ্যা চালান।",
  Blockers: "ব্লকার",
  "Check Approval Readiness": "অ্যাপ্রুভাল রেডিনেস চেক করুন",
  "Check whether the selected draft is ready for clinician approval.":
    "সিলেক্ট করা ড্রাফট ক্লিনিশিয়ান অনুমোদনের জন্য প্রস্তুত কিনা চেক করুন।",
  "Checking...": "চেক হচ্ছে...",
  "Clinician actions": "ক্লিনিশিয়ান অ্যাকশন",
  "Copy handoff": "হ্যান্ডঅফ কপি করুন",
  "Copy rationale": "রেশনাল কপি করুন",
  "Create Staff Handoff": "স্টাফ হ্যান্ডঅফ তৈরি করুন",
  "Creating handoff...": "হ্যান্ডঅফ তৈরি হচ্ছে...",
  Doctor: "ডাক্তার",
  "Evidence against risk": "ঝুঁকির বিপরীত প্রমাণ",
  "Evidence for risk": "ঝুঁকির পক্ষে প্রমাণ",
  "Close when": "ক্লোজ করুন যখন",
  "Do next": "এরপর করুন",
  "Escalate if": "এসক্যালেট করুন যদি",
  "Explain Risk": "ঝুঁকি ব্যাখ্যা করুন",
  "Explainable safety reasoning for review":
    "রিভিউয়ের জন্য ব্যাখ্যাযোগ্য সেফটি রিজনিং",
  "Explaining...": "ব্যাখ্যা হচ্ছে...",
  "Follow-up desk": "ফলো-আপ ডেস্ক",
  "Follow-up Scheduler": "ফলো-আপ শিডিউলার",
  "Follow-up scheduling failed.": "ফলো-আপ শিডিউলিং ব্যর্থ হয়েছে।",
  "Generate or select a case before creating a handoff.":
    "হ্যান্ডঅফ তৈরির আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a case before planning next steps.":
    "পরবর্তী ধাপ প্ল্যান করার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a case before scheduling follow-up.":
    "ফলো-আপ শিডিউল করার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a case before explaining risk.":
    "ঝুঁকি ব্যাখ্যার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a draft before checking approval.":
    "অ্যাপ্রুভাল চেক করার আগে একটি ড্রাফট তৈরি বা সিলেক্ট করুন।",
  "Handoff script": "হ্যান্ডঅফ স্ক্রিপ্ট",
  "Next-Step Navigator": "নেক্সট-স্টেপ নেভিগেটর",
  "Next-step planning failed.": "নেক্সট-স্টেপ প্ল্যানিং ব্যর্থ হয়েছে।",
  Owner: "মালিকানা",
  "Patient communication": "রোগীর যোগাযোগ",
  "Plan Next Steps": "পরবর্তী ধাপ প্ল্যান করুন",
  "Planning...": "প্ল্যান হচ্ছে...",
  "Missing checks": "মিসিং চেক",
  Nurse: "নার্স",
  "Patient safety net": "রোগীর সেফটি নেট",
  "Ready signals": "রেডি সিগনাল",
  Receptionist: "রিসেপশনিস্ট",
  "Risk explanation failed.": "ঝুঁকি ব্যাখ্যা ব্যর্থ হয়েছে।",
  "Risk level": "ঝুঁকির স্তর",
  "Risk Rationale": "ঝুঁকির রেশনাল",
  Reminders: "রিমাইন্ডার",
  "Schedule Follow-up": "ফলো-আপ শিডিউল করুন",
  "Schedule callback timing and escalation rules after a draft is ready.":
    "ড্রাফট প্রস্তুত হওয়ার পর কলব্যাক টাইমিং ও এসক্যালেশন রুল শিডিউল করুন।",
  "Scheduling...": "শিডিউল হচ্ছে...",
  "Safety notes": "সেফটি নোট",
  "Signoff checklist": "সাইনঅফ চেকলিস্ট",
  "Staff handoff failed.": "স্টাফ হ্যান্ডঅফ ব্যর্থ হয়েছে।",
  "Staff Handoff": "স্টাফ হ্যান্ডঅফ",
  Uncertainty: "অনিশ্চয়তা",
  Urgency: "জরুরিতা",
  "Ask what to do next and the app will suggest safe workflow commands.":
    "এরপর কী করতে হবে জিজ্ঞেস করুন, অ্যাপ নিরাপদ ওয়ার্কফ্লো কমান্ড সাজেস্ট করবে।",
  "AI queue summary for the next safe move":
    "পরবর্তী নিরাপদ মুভের জন্য AI কিউ সারাংশ",
  "Ask Command Copilot to brief the clinic, or run it here.":
    "কমান্ড কোপাইলটকে ক্লিনিক ব্রিফ করতে বলুন, অথবা এখানে চালান।",
  "Agent actions will appear here after you run a command.":
    "কমান্ড চালানোর পরে এজেন্ট অ্যাকশন এখানে দেখা যাবে।",
  age: "বয়স",
  and: "এবং",
  "AI Run Receipts": "AI রান রিসিট",
  "Ask Copilot...": "কোপাইলটকে জিজ্ঞেস করুন...",
  Actions: "অ্যাকশন",
  "Answer this patient question in Bangla": "এই রোগীর প্রশ্নের উত্তর বাংলায় দিন",
  "Ask for the next action, a draft, a safety check, or a patient explanation. Tools run inline and remain draft-only.":
    "পরবর্তী অ্যাকশন, ড্রাফট, সেফটি চেক বা রোগীর ব্যাখ্যা চাইুন। টুল ইনলাইন চলে এবং ড্রাফট-অনলি থাকে।",
  "Attach note": "নোট অ্যাটাচ করুন",
  "Audio/Bangla": "অডিও/বাংলা",
  "Clinical draft generation": "ক্লিনিক্যাল ড্রাফট জেনারেশন",
  "Clinical review stays required": "ক্লিনিক্যাল রিভিউ বাধ্যতামূলক থাকে",
  context: "কনটেক্সট",
  "Copilot command room": "কোপাইলট কমান্ড রুম",
  "Copilot can draft, summarize, and route work. It should not diagnose, prescribe, or bypass clinician approval.":
    "কোপাইলট ড্রাফট, সারাংশ ও কাজ রাউট করতে পারে। এটি রোগ নির্ণয়, প্রেসক্রাইব বা ক্লিনিশিয়ান অনুমোদন বাইপাস করবে না।",
  "Discover all external-agent tools.": "সব এক্সটার্নাল-এজেন্ট টুল খুঁজে দেখুন।",
  done: "শেষ",
  "Doctor Agent": "ডাক্তার এজেন্ট",
  draft: "ড্রাফট",
  "Draft support only. Missing vitals, allergy status, and escalation triggers remain visible.":
    "শুধু ড্রাফট সহায়তা। মিসিং ভাইটাল, অ্যালার্জি স্ট্যাটাস ও এসক্যালেশন ট্রিগার দৃশ্যমান থাকে।",
  "Every AI action shows inputs, safety checks, review state, and audit context":
    "প্রতিটি AI অ্যাকশনে ইনপুট, সেফটি চেক, রিভিউ স্টেট ও অডিট কনটেক্সট দেখা যায়",
  "Explain this in simple Bangla": "এটা সহজ বাংলায় ব্যাখ্যা করুন",
  "Extract this prescription and lab report":
    "এই প্রেসক্রিপশন ও ল্যাব রিপোর্ট এক্সট্র্যাক্ট করুন",
  "I can help with queue triage, missing clinical details, patient-friendly Bangla, follow-up ownership, and print-ready drafts.":
    "আমি কিউ ট্রায়াজ, মিসিং ক্লিনিক্যাল তথ্য, রোগীবান্ধব বাংলা, ফলো-আপ মালিকানা ও প্রিন্ট-রেডি ড্রাফটে সাহায্য করতে পারি।",
  "I found": "আমি পেয়েছি",
  "I received the command, but no visible workflow action was returned.":
    "কমান্ড পেয়েছি, কিন্তু দৃশ্যমান কোনো ওয়ার্কফ্লো অ্যাকশন ফেরত আসেনি।",
  Input: "ইনপুট",
  "Inspect the role-aware tool registry.": "রোল-অওয়ার টুল রেজিস্ট্রি দেখুন।",
  "Inspect tools, copy payloads, and run demo-safe external-agent calls":
    "টুল দেখুন, পেলোড কপি করুন, এবং ডেমো-সেফ এক্সটার্নাল-এজেন্ট কল চালান",
  "Intake readiness check": "ইনটেক রেডিনেস চেক",
  "MCP explorer response": "MCP এক্সপ্লোরার রেসপন্স",
  "MCP Explorer": "MCP এক্সপ্লোরার",
  "min saved": "মিনিট সাশ্রয়",
  "missing questions require human review.": "মিসিং প্রশ্নের জন্য মানব রিভিউ দরকার।",
  "needs review": "রিভিউ দরকার",
  needs_review: "রিভিউ দরকার",
  "No active patient": "অ্যাকটিভ রোগী নেই",
  "No active patient selected.": "কোনো অ্যাকটিভ রোগী সিলেক্ট করা নেই।",
  "Open case": "কেস খুলুন",
  "Operational proof points the clinic can act on":
    "অপারেশনাল প্রমাণ, যার ওপর ক্লিনিক অ্যাকশন নিতে পারে",
  "Ops Agent": "অপস এজেন্ট",
  Output: "আউটপুট",
  "Patient thread": "রোগী থ্রেড",
  "Prepare follow-up ownership and patient communication":
    "ফলো-আপ মালিকানা ও রোগীর যোগাযোগ প্রস্তুত করুন",
  "Queue ops": "কিউ অপস",
  "Brief me on today's queue pressure and red flags":
    "আজকের কিউ চাপ ও রেড ফ্ল্যাগ নিয়ে আমাকে ব্রিফ করুন",
  "questions found": "প্রশ্ন পাওয়া",
  "Recent runs": "সাম্প্রতিক রান",
  "Review this case and suggest the next safest action":
    "এই কেস রিভিউ করে পরবর্তী সবচেয়ে নিরাপদ অ্যাকশন সাজেস্ট করুন",
  "Review this patient and tell me the next safest action":
    "এই রোগী রিভিউ করে পরবর্তী সবচেয়ে নিরাপদ অ্যাকশন বলুন",
  "Run an MCP call.": "একটি MCP কল চালান।",
  "Run MCP call": "MCP কল চালান",
  "Run the safety blocker check.": "সেফটি ব্লকার চেক চালান।",
  "Run through local LM Studio": "লোকাল LM Studio দিয়ে চালান",
  "Running MCP call": "MCP কল চলছে",
  Running: "চলছে",
  "Safety review": "সেফটি রিভিউ",
  "List clinical blockers before print or closeout":
    "প্রিন্ট বা ক্লোজআউটের আগে ক্লিনিক্যাল ব্লকার তালিকা করুন",
  "SOAP support, red flags, handout, follow-up":
    "SOAP সহায়তা, রেড ফ্ল্যাগ, হ্যান্ডআউট, ফলো-আপ",
  "Structured workflow context": "স্ট্রাকচার্ড ওয়ার্কফ্লো কনটেক্সট",
  "The command could not be completed.": "কমান্ড সম্পন্ন করা যায়নি।",
  "What is missing?": "কী মিসিং?",
  Role: "রোল",
  error: "এরর",
  idle: "আইডল",
  "missing questions": "মিসিং প্রশ্ন",
  "open safety gates": "ওপেন সেফটি গেট",
  run: "রান",
  running: "চলছে",
  unknown: "অজানা",
  "Brief Clinic Queue": "ক্লিনিক কিউ ব্রিফ করুন",
  "Briefing...": "ব্রিফিং হচ্ছে...",
  "Check medicine safety": "ওষুধের সেফটি চেক করুন",
  "Checks clarity, allergies, and warning language":
    "ক্ল্যারিটি, অ্যালার্জি ও সতর্কতার ভাষা চেক করে",
  "Clarifying questions": "ক্ল্যারিফাইং প্রশ্ন",
  "Clinic Briefing": "ক্লিনিক ব্রিফিং",
  "Clinic briefing failed.": "ক্লিনিক ব্রিফিং ব্যর্থ হয়েছে।",
  "Copy briefing": "ব্রিফিং কপি করুন",
  "Copy handout": "হ্যান্ডআউট কপি করুন",
  Care: "যত্ন",
  "Draft medicine instructions": "ড্রাফট ওষুধ নির্দেশনা",
  "Follow-up actions": "ফলো-আপ অ্যাকশন",
  Issues: "ইস্যু",
  "Medicine check failed.": "ওষুধ চেক ব্যর্থ হয়েছে।",
  Medicine: "ওষুধ",
  "Medicine Safety": "ওষুধ সেফটি",
  "Next best actions": "নেক্সট বেস্ট অ্যাকশন",
  "Paperwork gaps": "পেপারওয়ার্ক গ্যাপ",
  Paperwork: "পেপারওয়ার্ক",
  "Patient instructions": "রোগীর নির্দেশনা",
  "Print handout": "হ্যান্ডআউট প্রিন্ট করুন",
  Print: "প্রিন্ট",
  "Generate a draft to create a shareable handout.":
    "শেয়ার করা যায় এমন হ্যান্ডআউট তৈরি করতে একটি ড্রাফট জেনারেট করুন।",
  "Urgent return": "জরুরি ফেরত আসা",
  "Priority patients": "অগ্রাধিকার রোগী",
  risk: "ঝুঁকি",
  Approve: "অনুমোদন করুন",
  approved: "অনুমোদিত",
  "Convex realtime queue": "Convex রিয়েলটাইম কিউ",
  "Filter by severity": "সিভিয়ারিটি দিয়ে ফিল্টার করুন",
  "Filter by status": "স্ট্যাটাস দিয়ে ফিল্টার করুন",
  flags: "ফ্ল্যাগ",
  "Follow-up": "ফলো-আপ",
  followup: "ফলো-আপ",
  "Follow-up clock": "ফলো-আপ ঘড়ি",
  "Generated cases will appear here.": "জেনারেট করা কেস এখানে দেখা যাবে।",
  Handout: "হ্যান্ডআউট",
  handout: "হ্যান্ডআউট",
  "just arrived": "এখনই এসেছে",
  "Live Case Board": "লাইভ কেস বোর্ড",
  "Move to follow-up": "ফলো-আপে নিন",
  "Move to handout": "হ্যান্ডআউটে নিন",
  "Open urgent case": "জরুরি কেস খুলুন",
  "owner: doctor": "মালিকানা: ডাক্তার",
  "owner: follow-up desk": "মালিকানা: ফলো-আপ ডেস্ক",
  "owner: nurse": "মালিকানা: নার্স",
  "owner: reception": "মালিকানা: রিসেপশন",
  "Patient, complaint, language...": "রোগী, অভিযোগ, ভাষা...",
  priority: "অগ্রাধিকার",
  "Red Flag Lane": "রেড ফ্ল্যাগ লেন",
  "red flag lane": "রেড ফ্ল্যাগ লেন",
  review: "রিভিউ",
  "routine lane": "রুটিন লেন",
  "Search cases": "কেস খুঁজুন",
  "Select case": "কেস সিলেক্ট করুন",
  status: "স্ট্যাটাস",
  "timing not set": "টাইমিং সেট করা নেই",
  waiting: "অপেক্ষমাণ",
  yrs: "বছর",
  all: "সব",
  confidence: "কনফিডেন্স",
  high: "উচ্চ",
  "high priority": "উচ্চ অগ্রাধিকার",
  blocked: "ব্লকড",
  Clarify: "ক্ল্যারিফাই",
  Labs: "ল্যাব",
  low: "নিম্ন",
  "low priority": "নিম্ন অগ্রাধিকার",
  Medicines: "ওষুধ",
  medium: "মাঝারি",
  "medium priority": "মাঝারি অগ্রাধিকার",
  ready: "রেডি",
  "Safety issues": "সেফটি ইস্যু",
  urgent: "জরুরি",
  urgency: "জরুরিতা",
  Vitals: "ভাইটাল",
  "Access for BD clinics": "বাংলাদেশি ক্লিনিকের অ্যাক্সেস",
  "AI drafts remain clinician-review material.":
    "AI ড্রাফট ক্লিনিশিয়ান-রিভিউ ম্যাটেরিয়াল হিসেবেই থাকে।",
  "All gates clear": "সব গেট ক্লিয়ার",
  "Audit log records important auth, AI, and case workflow actions.":
    "অডিট লগ গুরুত্বপূর্ণ অথ, AI ও কেস ওয়ার্কফ্লো অ্যাকশন রেকর্ড করে।",
  "Bangla-first copy, print slips, mobile layout, and low literacy.":
    "বাংলা-ফার্স্ট কপি, প্রিন্ট স্লিপ, মোবাইল লেআউট ও লো লিটারেসি।",
  "Bangla/mixed": "বাংলা/মিশ্র",
  "Bilingual handout is generated for clinician review.":
    "ক্লিনিশিয়ান রিভিউয়ের জন্য দ্বিভাষিক হ্যান্ডআউট জেনারেট হয়।",
  "Build up": "আরও তৈরি করুন",
  "Capture or clean the reception note before AI drafting.":
    "AI ড্রাফটের আগে রিসেপশন নোট নিন বা পরিষ্কার করুন।",
  "Check the draft, handoff, risk explanation, and approval status.":
    "ড্রাফট, হ্যান্ডঅফ, ঝুঁকি ব্যাখ্যা ও অ্যাপ্রুভাল স্ট্যাটাস চেক করুন।",
  "Clinic ready": "ক্লিনিক রেডি",
  "Clinic workflow readiness": "ক্লিনিক ওয়ার্কফ্লো রেডিনেস",
  "Clinical Safety Gates": "ক্লিনিক্যাল সেফটি গেট",
  "Clinician approval before handout": "হ্যান্ডআউটের আগে ক্লিনিশিয়ান অনুমোদন",
  "Closed loop": "ক্লোজড লুপ",
  "Draft support should be reviewed before handout, follow-up, or discharge packet.":
    "হ্যান্ডআউট, ফলো-আপ বা ডিসচার্জ প্যাকেটের আগে ড্রাফট সহায়তা রিভিউ করা উচিত।",
  "Human review, red flags, medicine clarity, and audit trail.":
    "মানব রিভিউ, রেড ফ্ল্যাগ, ওষুধের স্পষ্টতা ও অডিট ট্রেইল।",
  "Intake, draft, handout, follow-up, referral, and closeout.":
    "ইনটেক, ড্রাফট, হ্যান্ডআউট, ফলো-আপ, রেফারাল ও ক্লোজআউট।",
  "Load a realistic case, generate the draft, and open presentation mode.":
    "বাস্তবসম্মত কেস লোড করুন, ড্রাফট জেনারেট করুন, এবং প্রেজেন্টেশন মোড খুলুন।",
  "Low-Connectivity Mode": "লো-কানেক্টিভিটি মোড",
  "Medicine and allergy clarity": "ওষুধ ও অ্যালার্জি স্পষ্টতা",
  "Medicine instructions need dose clarity and allergy status before patient instructions.":
    "রোগীর নির্দেশনার আগে ওষুধে ডোজ স্পষ্টতা ও অ্যালার্জি স্ট্যাটাস দরকার।",
  "Nearly ready": "প্রায় রেডি",
  "No local drafts are waiting to sync.": "সিঙ্কের অপেক্ষায় কোনো লোকাল ড্রাফট নেই।",
  "Offline intake note": "অফলাইন ইনটেক নোট",
  "Offline intake queue active": "অফলাইন ইনটেক কিউ অ্যাকটিভ",
  "Online with local backup queue": "লোকাল ব্যাকআপ কিউসহ অনলাইন",
  "Open Case": "কেস খুলুন",
  "Open Copilot": "কোপাইলট খুলুন",
  "Open Ops": "অপস খুলুন",
  open: "ওপেন",
  "Patient-facing output must include urgent-return warnings before printing or closeout.":
    "প্রিন্ট বা ক্লোজআউটের আগে রোগীমুখী আউটপুটে জরুরি ফেরত সতর্কতা থাকতে হবে।",
  "Pregnancy, child cases, chest pain, or breathing symptoms must stay in clinician review.":
    "প্রেগন্যান্সি, শিশু কেস, বুক ব্যথা বা শ্বাসকষ্ট ক্লিনিশিয়ান রিভিউতেই থাকতে হবে।",
  "Pregnancy, child, chest-pain escalation": "প্রেগন্যান্সি, শিশু, বুক ব্যথা এসক্যালেশন",
  "Printable clinic slip and mobile layout support real clinic desks.":
    "প্রিন্টযোগ্য ক্লিনিক স্লিপ ও মোবাইল লেআউট বাস্তব ক্লিনিক ডেস্কে সহায়ক।",
  "Proof points": "প্রুফ পয়েন্ট",
  "Queue a quick note when the clinic internet is weak...":
    "ক্লিনিক ইন্টারনেট দুর্বল হলে দ্রুত নোট কিউ করুন...",
  "Queue local draft": "লোকাল ড্রাফট কিউ করুন",
  queued: "কিউড",
  Readiness: "রেডিনেস",
  "Record BP, temperature, pulse, SpO2, or equivalent triage vitals before signoff.":
    "সাইনঅফের আগে BP, তাপমাত্রা, পালস, SpO2 বা সমতুল্য ট্রায়াজ ভাইটাল রেকর্ড করুন।",
  "Required checks before print, approval, and closeout":
    "প্রিন্ট, অনুমোদন ও ক্লোজআউটের আগে বাধ্যতামূলক চেক",
  "Return warnings confirmed": "রিটার্ন সতর্কতা কনফার্মড",
  "Review queue pressure, follow-ups, trends, model, and audit trail.":
    "কিউ চাপ, ফলো-আপ, ট্রেন্ড, মডেল ও অডিট ট্রেইল রিভিউ করুন।",
  "Run the guided workflow or jump straight into the work area you need.":
    "গাইডেড ওয়ার্কফ্লো চালান বা প্রয়োজনীয় ওয়ার্ক এরিয়ায় সরাসরি যান।",
  "Safety banner and approval guard frame the AI as draft support.":
    "সেফটি ব্যানার ও অ্যাপ্রুভাল গার্ড AI-কে ড্রাফট সহায়তা হিসেবে ফ্রেম করে।",
  "Safety controls": "সেফটি কন্ট্রোল",
  "Safety, access, workflow, and operating proof":
    "সেফটি, অ্যাক্সেস, ওয়ার্কফ্লো ও অপারেটিং প্রমাণ",
  "Seed cases": "সিড কেস",
  "Seed cases, impact metrics, presentation mode, and live AI.":
    "সিড কেস, ইমপ্যাক্ট মেট্রিক, প্রেজেন্টেশন মোড ও লাইভ AI।",
  "Six Bangladesh-native seed cases prove the workflow beyond one happy path.":
    "বাংলাদেশ-নেটিভ ছয়টি সিড কেস এক হ্যাপি পাথের বাইরে ওয়ার্কফ্লো প্রমাণ করে।",
  "Start guided workflow": "গাইডেড ওয়ার্কফ্লো শুরু করুন",
  "Start here": "এখান থেকে শুরু করুন",
  Sync: "সিঙ্ক",
  synced: "সিঙ্কড",
  syncing: "সিঙ্ক হচ্ছে",
  "Sync queued draft": "কিউড ড্রাফট সিঙ্ক করুন",
  "Unnamed offline intake": "নামহীন অফলাইন ইনটেক",
  "unnamed patient": "নামহীন রোগী",
  "Vitals required": "ভাইটাল প্রয়োজন",
  "Workflow coverage": "ওয়ার্কফ্লো কভারেজ",
  "Workflow proof": "ওয়ার্কফ্লো প্রমাণ",
  "Anonymized demo signals": "অ্যানোনিমাইজড ডেমো সিগনাল",
  "Approvals Inbox": "অ্যাপ্রুভাল ইনবক্স",
  "Audit events will appear after actions.": "অ্যাকশনের পরে অডিট ইভেন্ট দেখা যাবে।",
  "Audit Trail": "অডিট ট্রেইল",
  "Bangla or mixed-language intakes": "বাংলা বা মিশ্র ভাষার ইনটেক",
  "Built for responsible demo judging": "দায়িত্বশীল ডেমো জাজিংয়ের জন্য তৈরি",
  "Close the loop after discharge": "ডিসচার্জের পরে লুপ ক্লোজ করুন",
  "Close presentation mode": "প্রেজেন্টেশন মোড বন্ধ করুন",
  "Clinic Trends": "ক্লিনিক ট্রেন্ড",
  "Due Follow-ups": "ডিউ ফলো-আপ",
  "Every important AI and workflow action": "প্রতিটি গুরুত্বপূর্ণ AI ও ওয়ার্কফ্লো অ্যাকশন",
  "Fast Demo Keys": "ফাস্ট ডেমো কী",
  "Focus Command Copilot": "কমান্ড কোপাইলটে ফোকাস করুন",
  "Follow-up timing not set": "ফলো-আপ টাইমিং সেট করা নেই",
  "Keyboard-first clinic operation": "কীবোর্ড-ফার্স্ট ক্লিনিক অপারেশন",
  "No follow-up cases are queued.": "কোনো ফলো-আপ কেস কিউতে নেই।",
  "One place for signoff, escalation acknowledgment, return warnings, and print approval":
    "সাইনঅফ, এসক্যালেশন স্বীকৃতি, রিটার্ন সতর্কতা ও প্রিন্ট অনুমোদনের এক জায়গা",
  "Presentation mode": "প্রেজেন্টেশন মোড",
  "Safety Frame": "সেফটি ফ্রেম",
  "AI drafts notes. Doctors decide care.":
    "AI নোট ড্রাফট করে। চিকিৎসার সিদ্ধান্ত ডাক্তার নেন।",
  "No diagnosis claims. No autonomous prescribing.":
    "রোগ নির্ণয়ের দাবি নয়। স্বয়ংক্রিয় প্রেসক্রাইবিং নয়।",
  "Patient copy prioritizes plain language and return warnings.":
    "রোগীর কপিতে সহজ ভাষা ও রিটার্ন সতর্কতাকে অগ্রাধিকার দেওয়া হয়।",
  "High priority": "উচ্চ অগ্রাধিকার",
  "Medium priority": "মাঝারি অগ্রাধিকার",
  "Low priority": "নিম্ন অগ্রাধিকার",
  "Needs follow-up": "ফলো-আপ দরকার",
  Operate: "অপারেট",
  Navigate: "নেভিগেট",
  Demo: "ডেমো",
  "AI setup": "AI সেটআপ",
  "answer question": "প্রশ্নের উত্তর",
  "triage reply": "রিপ্লাই ট্রায়াজ",
  "close visit": "ভিজিট ক্লোজ",
  undo: "আনডু",
  "brief queue": "কিউ ব্রিফ",
  "show high priority": "উচ্চ অগ্রাধিকার দেখান",
  "clear filters": "ফিল্টার ক্লিয়ার",
  "full workflow": "ফুল ওয়ার্কফ্লো",
  "guided workflow": "গাইডেড ওয়ার্কফ্লো",
  "open presentation": "প্রেজেন্টেশন খুলুন",
  "extract document": "ডকুমেন্ট এক্সট্র্যাক্ট",
  "clean intake": "ইনটেক পরিষ্কার",
  "check medicines": "ওষুধ চেক",
  "AI Model": "AI মডেল",
  "AI-drafted SMS or WhatsApp callback": "AI-ড্রাফটেড SMS বা WhatsApp কলব্যাক",
  Ask: "জিজ্ঞেস করুন",
  "Ask a question about the selected case.":
    "সিলেক্ট করা কেস সম্পর্কে একটি প্রশ্ন করুন।",
  "Ask about selected case": "সিলেক্ট করা কেস সম্পর্কে জিজ্ঞেস করুন",
  "Ask This Case": "এই কেস জিজ্ঞেস করুন",
  "Clinical summary": "ক্লিনিক্যাল সারাংশ",
  "Clinician checklist": "ক্লিনিশিয়ান চেকলিস্ট",
  "Clinician-reviewable referral or visit summary":
    "ক্লিনিশিয়ান-রিভিউযোগ্য রেফারাল বা ভিজিট সারাংশ",
  "Compose a reviewed callback after a draft is generated.":
    "ড্রাফট তৈরি হওয়ার পরে রিভিউড কলব্যাক লিখুন।",
  "Compose Follow-up": "ফলো-আপ লিখুন",
  "Composing...": "লেখা হচ্ছে...",
  "Explain this to the patient in simple Bangla": "এটা রোগীকে সহজ বাংলায় ব্যাখ্যা করুন",
  "Follow-up composition failed.": "ফলো-আপ লেখা ব্যর্থ হয়েছে।",
  "Follow-up message": "ফলো-আপ মেসেজ",
  "Follow-up Messenger": "ফলো-আপ মেসেঞ্জার",
  "Follow-up queued for staff review": "স্টাফ রিভিউয়ের জন্য ফলো-আপ কিউ হয়েছে",
  "Free-text AI help for the selected patient":
    "সিলেক্ট করা রোগীর জন্য ফ্রি-টেক্সট AI সহায়তা",
  "Generate a draft, then ask for a referral or family visit summary.":
    "একটি ড্রাফট জেনারেট করুন, তারপর রেফারাল বা পরিবারের ভিজিট সারাংশ চাইুন।",
  "Generate or select a case before composing follow-up.":
    "ফলো-আপ লেখার আগে একটি কেস জেনারেট বা সিলেক্ট করুন।",
  "Generate or select a case before creating paperwork.":
    "পেপারওয়ার্ক তৈরির আগে একটি কেস জেনারেট বা সিলেক্ট করুন।",
  "Generation model": "জেনারেশন মডেল",
  "Key findings": "মূল ফাইন্ডিং",
  "Make a follow-up call script": "একটি ফলো-আপ কল স্ক্রিপ্ট তৈরি করুন",
  "Paperwork generation failed.": "পেপারওয়ার্ক জেনারেশন ব্যর্থ হয়েছে।",
  Patient: "রোগী",
  "Queue for review": "রিভিউয়ের জন্য কিউ করুন",
  Reason: "কারণ",
  Recipient: "প্রাপক",
  Referral: "রেফারাল",
  "Referral or visit summary": "রেফারাল বা ভিজিট সারাংশ",
  "Referral Writer": "রেফারাল রাইটার",
  "Requested action": "প্রয়োজনীয় অ্যাকশন",
  "Switch provider model for demos": "ডেমোর জন্য প্রোভাইডার মডেল বদলান",
  "Best live-demo balance": "লাইভ ডেমোর সেরা ভারসাম্য",
  "Fastest low-cost mode": "সবচেয়ে দ্রুত কম খরচের মোড",
  Local: "লোকাল",
  "Use server configuration": "সার্ভার কনফিগারেশন ব্যবহার করুন",
  sms: "SMS",
  "Visit summary": "ভিজিট সারাংশ",
  "What are the safety-net warnings?": "সেফটি-নেট সতর্কতাগুলো কী?",
  "What should reception ask next?": "রিসেপশনের এরপর কী জিজ্ঞেস করা উচিত?",
  "Write Paperwork": "পেপারওয়ার্ক লিখুন",
  "Writing...": "লেখা হচ্ছে...",
  via: "মাধ্যম",
  whatsapp: "WhatsApp",
  "Command Copilot input": "কমান্ড কোপাইলট ইনপুট",
  "Command failed.": "কমান্ড ব্যর্থ হয়েছে।",
  "Type your way through the clinic workflow": "টাইপ করে ক্লিনিক ওয়ার্কফ্লো চালান",
  Preview: "প্রিভিউ",
  "Preview failed.": "প্রিভিউ ব্যর্থ হয়েছে।",
  "Previewing...": "প্রিভিউ হচ্ছে...",
  Run: "চালান",
  "Run again": "আবার চালান",
  "Recent command trail": "সাম্প্রতিক কমান্ড ট্রেইল",
  "Type a command first.": "আগে একটি কমান্ড লিখুন।",
  "Run the full clinic workflow": "ফুল ক্লিনিক ওয়ার্কফ্লো চালান",
  "Run the guided clinic workflow": "গাইডেড ক্লিনিক ওয়ার্কফ্লো চালান",
  "Undo last command": "শেষ কমান্ড আনডু করুন",
  "Load dengue watch and generate a draft": "ডেঙ্গু ওয়াচ লোড করে ড্রাফট জেনারেট করুন",
  "Switch to Bangla and open presentation mode": "বাংলায় বদলে প্রেজেন্টেশন মোড খুলুন",
  "Approve this case and move it to handout": "এই কেস অনুমোদন করে হ্যান্ডআউটে নিন",
  "Check if this case is ready to approve":
    "এই কেস অনুমোদনের জন্য প্রস্তুত কিনা চেক করুন",
  "Search for Farzana and show high priority cases":
    "Farzana খুঁজুন এবং উচ্চ অগ্রাধিকার কেস দেখান",
  "Use the fastest model and clear filters":
    "দ্রুততম মডেল ব্যবহার করুন এবং ফিল্টার ক্লিয়ার করুন",
  "Mark this patient for follow-up": "এই রোগীকে ফলো-আপের জন্য মার্ক করুন",
  "Schedule follow-up for this patient": "এই রোগীর ফলো-আপ শিডিউল করুন",
  "Close this visit safely": "এই ভিজিট নিরাপদে ক্লোজ করুন",
  "Compose a WhatsApp follow-up for this patient":
    "এই রোগীর জন্য WhatsApp ফলো-আপ লিখুন",
  "Triage this patient reply": "এই রোগীর রিপ্লাই ট্রায়াজ করুন",
  "Write a referral letter for this patient": "এই রোগীর জন্য রেফারাল লেটার লিখুন",
  "Create a visit summary for the family": "পরিবারের জন্য ভিজিট সারাংশ তৈরি করুন",
  "Brief me on today's clinic queue": "আজকের ক্লিনিক কিউ নিয়ে আমাকে ব্রিফ করুন",
  "Tell me what to do next for this case": "এই কেসে এরপর কী করতে হবে বলুন",
  "Create a nurse handoff and receptionist task list":
    "নার্স হ্যান্ডঅফ ও রিসেপশনিস্ট টাস্ক লিস্ট তৈরি করুন",
  "Clean this intake and extract vitals": "এই ইনটেক পরিষ্কার করে ভাইটাল বের করুন",
  "Explain why this case is risky": "এই কেস কেন ঝুঁকিপূর্ণ ব্যাখ্যা করুন",
  "Add a bleeding red flag and simplify the Bangla handout":
    "ব্লিডিং রেড ফ্ল্যাগ যোগ করে বাংলা হ্যান্ডআউট সহজ করুন",
  "Create a 52 year old male chest pain intake":
    "৫২ বছরের পুরুষ বুক ব্যথা ইনটেক তৈরি করুন",
  "Check medicine safety for paracetamol 500mg and antibiotic twice daily":
    "Paracetamol 500mg ও দিনে দুইবার antibiotic এর ওষুধ সেফটি চেক করুন",
  "Confirm vitals or mark unavailable": "ভাইটাল কনফার্ম করুন বা অনুপলব্ধ মার্ক করুন",
  "Vitals are required before a clinical draft or patient packet should be treated as ready.":
    "ক্লিনিক্যাল ড্রাফট বা রোগী প্যাকেট রেডি ধরা হওয়ার আগে ভাইটাল প্রয়োজন।",
  "Confirm medicine allergy status": "ওষুধ অ্যালার্জি স্ট্যাটাস কনফার্ম করুন",
  "Medicine-facing output must stay blocked until allergy status is checked.":
    "অ্যালার্জি স্ট্যাটাস চেক না হওয়া পর্যন্ত ওষুধ-সম্পর্কিত আউটপুট ব্লক থাকবে।",
  "Acknowledge red-flag escalation": "রেড-ফ্ল্যাগ এসক্যালেশন স্বীকার করুন",
  "red flags require human escalation acknowledgment.":
    "রেড ফ্ল্যাগের জন্য মানব এসক্যালেশন স্বীকৃতি দরকার।",
  "Approve patient packet for print": "প্রিন্টের জন্য রোগী প্যাকেট অনুমোদন করুন",
  "Handout, medicine slip, referral, and follow-up sheet are drafts until reviewed.":
    "হ্যান্ডআউট, মেডিসিন স্লিপ, রেফারাল ও ফলো-আপ শিট রিভিউ না হওয়া পর্যন্ত ড্রাফট।",
  "No approvals waiting": "কোনো অ্যাপ্রুভাল অপেক্ষায় নেই",
  "The current case has no detected approval blockers, but clinician review remains required.":
    "বর্তমান কেসে কোনো অ্যাপ্রুভাল ব্লকার ধরা পড়েনি, তবে ক্লিনিশিয়ান রিভিউ এখনও প্রয়োজন।",
  "Clinic team": "ক্লিনিক টিম",
  "Preview print": "প্রিন্ট প্রিভিউ",
  "Ask Copilot": "কোপাইলটকে জিজ্ঞেস করুন",
  "Assign owners": "মালিকানা অ্যাসাইন করুন",
  "Attach prescription or lab text": "প্রেসক্রিপশন বা ল্যাব টেক্সট অ্যাটাচ করুন",
  "Audio readout": "অডিও রিডআউট",
  "Approve handout": "হ্যান্ডআউট অনুমোদন করুন",
  "AI provider switcher": "AI প্রোভাইডার সুইচার",
  "Call sheet": "কল শিট",
  "Capture notes, vitals, documents, and missing basics.":
    "নোট, ভাইটাল, ডকুমেন্ট ও মিসিং বেসিক নিন।",
  "Check safety gates": "সেফটি গেট চেক করুন",
  "Check vitals": "ভাইটাল চেক করুন",
  "Clinic status": "ক্লিনিক স্ট্যাটাস",
  "Clinic workflow progress": "ক্লিনিক ওয়ার্কফ্লো প্রগ্রেস",
  complete: "সম্পন্ন",
  "Confirm allergies": "অ্যালার্জি কনফার্ম করুন",
  "Confirm teach-back": "টিচ-ব্যাক কনফার্ম করুন",
  "Doctor summary": "ডাক্তার সারাংশ",
  "Escalate red flags": "রেড ফ্ল্যাগ এসক্যালেট করুন",
  "Family must repeat before leaving:": "যাওয়ার আগে পরিবারকে পুনরাবৃত্তি করতে হবে:",
  "Focused workflows for each clinic worker":
    "প্রতিটি ক্লিনিক কর্মীর জন্য ফোকাসড ওয়ার্কফ্লো",
  "Generate or select a case to fill this printable packet.":
    "এই প্রিন্টযোগ্য প্যাকেট পূরণ করতে একটি কেস জেনারেট বা সিলেক্ট করুন।",
  "Handout, referral, medicine slip, call sheet, doctor summary":
    "হ্যান্ডআউট, রেফারাল, মেডিসিন স্লিপ, কল শিট, ডাক্তার সারাংশ",
  "Keep editing": "এডিটিং চালিয়ে যান",
  "Key warning": "মূল সতর্কতা",
  "Medicine slip": "মেডিসিন স্লিপ",
  "Monitor queue, staffing load, audit, and clinic readiness.":
    "কিউ, স্টাফিং লোড, অডিট ও ক্লিনিক রেডিনেস মনিটর করুন।",
  "No hard blocks": "কোনো হার্ড ব্লক নেই",
  "None documented": "কিছু ডকুমেন্টেড নেই",
  "Own call-backs, reply triage, and patient understanding.":
    "কলব্যাক, রিপ্লাই ট্রায়াজ ও রোগীর বোঝাপড়া পরিচালনা করুন।",
  "Page-aware help with chat, tools, approvals, and safety context.":
    "চ্যাট, টুল, অ্যাপ্রুভাল ও সেফটি কনটেক্সটসহ পেজ-অওয়ার সহায়তা।",
  "Patient handout": "রোগীর হ্যান্ডআউট",
  "Patient Literacy Modes": "রোগী লিটারেসি মোড",
  Pictogram: "পিক্টোগ্রাম",
  "Prepare triage, red flags, and staff handoff.":
    "ট্রায়াজ, রেড ফ্ল্যাগ ও স্টাফ হ্যান্ডঅফ প্রস্তুত করুন।",
  Provider: "প্রোভাইডার",
  "Print Preview": "প্রিন্ট প্রিভিউ",
  "Read patient instructions aloud": "রোগীর নির্দেশনা জোরে পড়ুন",
  Reception: "রিসেপশন",
  "Record vitals": "ভাইটাল রেকর্ড করুন",
  "Referral cover note": "রেফারাল কভার নোট",
  "Register patient": "রোগী রেজিস্টার করুন",
  "Return warnings": "রিটার্ন সতর্কতা",
  "Review audit trail": "অডিট ট্রেইল রিভিউ করুন",
  "Review draft": "ড্রাফট রিভিউ করুন",
  "Review SOAP draft, approve, and close safely.":
    "SOAP ড্রাফট রিভিউ, অনুমোদন ও নিরাপদে ক্লোজ করুন।",
  "Review the packet before sending it to the printer.":
    "প্রিন্টারে পাঠানোর আগে প্যাকেট রিভিউ করুন।",
  "Role View": "রোল ভিউ",
  "Use Google Gemini through AI SDK": "AI SDK দিয়ে Google Gemini ব্যবহার করুন",
  "Schedule callback": "কলব্যাক শিডিউল করুন",
  "Simple Bangla": "সহজ বাংলা",
  "Simple Bangla, pictograms, audio, and teach-back confirmation":
    "সহজ বাংলা, পিক্টোগ্রাম, অডিও ও টিচ-ব্যাক কনফার্মেশন",
  "steps completed": "ধাপ সম্পন্ন",
  "Switch patient literacy mode to": "রোগী লিটারেসি মোড বদলান",
  "Switch role view to": "রোল ভিউ বদলান",
  "Triage replies": "রিপ্লাই ট্রায়াজ করুন",
  "Uses the device speech engine when available; staff should still review wording.":
    "ডিভাইস স্পিচ ইঞ্জিন থাকলে তা ব্যবহার করে; তবু স্টাফের ভাষা রিভিউ করা উচিত।",
  "Watch queue pressure": "কিউ চাপ দেখুন",
  "What care steps will happen at home.": "বাড়িতে কোন যত্নের ধাপ হবে।",
  "When and how follow-up will happen.": "কখন এবং কীভাবে ফলো-আপ হবে।",
  "Which danger signs require urgent return.":
    "কোন বিপদ চিহ্নে জরুরি ফেরত আসতে হবে।",
  "Visit Journey": "ভিজিট জার্নি",
  "One glance from intake to closeout": "ইনটেক থেকে ক্লোজআউট এক নজরে",
  "Next move": "পরবর্তী মুভ",
  Intake: "ইনটেক",
  "Capture patient, age, and story.": "রোগী, বয়স ও গল্প নিন।",
  "Finish enough intake detail for AI support.":
    "AI সহায়তার জন্য যথেষ্ট ইনটেক তথ্য সম্পন্ন করুন।",
  "Reception intake is ready.": "রিসেপশন ইনটেক প্রস্তুত।",
  "AI draft": "AI ড্রাফট",
  "Generate draft documentation.": "ড্রাফট ডকুমেন্টেশন জেনারেট করুন।",
  "Create the clinician-review draft.": "ক্লিনিশিয়ান-রিভিউ ড্রাফট তৈরি করুন।",
  "Draft, handout, and checklist are generated.":
    "ড্রাফট, হ্যান্ডআউট ও চেকলিস্ট জেনারেট হয়েছে।",
  "Review missing questions and red flags.": "মিসিং প্রশ্ন ও রেড ফ্ল্যাগ রিভিউ করুন।",
  "Clinician reviews risks and missing checks.":
    "ক্লিনিশিয়ান ঝুঁকি ও মিসিং চেক রিভিউ করেন।",
  "Safety signals are visible for clinician review.":
    "ক্লিনিশিয়ান রিভিউয়ের জন্য সেফটি সিগনাল দৃশ্যমান।",
  "Prepare patient-facing instructions.": "রোগীমুখী নির্দেশনা প্রস্তুত করুন।",
  "Clinician approves wording before sharing.":
    "শেয়ার করার আগে ক্লিনিশিয়ান ভাষা অনুমোদন করেন।",
  "Patient handout is ready to share.": "রোগীর হ্যান্ডআউট শেয়ার করার জন্য প্রস্তুত।",
  "Confirm the family understood.": "পরিবার বুঝেছে কিনা কনফার্ম করুন।",
  "Ask the family to repeat the plan.": "পরিবারকে প্ল্যান পুনরাবৃত্তি করতে বলুন।",
  "Understanding is confirmed by staff.": "স্টাফ বোঝাপড়া কনফার্ম করেছেন।",
  "Assign callback or closeout.": "কলব্যাক বা ক্লোজআউট অ্যাসাইন করুন।",
  "Schedule callback and closure owner.": "কলব্যাক ও ক্লোজার মালিকানা শিডিউল করুন।",
  "Follow-up workflow is queued.": "ফলো-আপ ওয়ার্কফ্লো কিউ হয়েছে।",
};

export function useClinicText() {
  const { language } = useLanguage();
  return useCallback(
    (text: string) => (language === "bn" ? (clinicTextBn[text] ?? text) : text),
    [language],
  );
}
