"use client";

import { useCallback } from "react";
import { useLanguage } from "@/features/language/language-context";

const clinicTextBn: Record<string, string> = {
  "AI drafts safe Bangla-English answers for clinician review":
    "ক্লিনিশিয়ান রিভিউয়ের জন্য AI নিরাপদ বাংলা-ইংরেজি উত্তর ড্রাফট করে",
  "AI reviews incoming patient replies after follow-up":
    "ফলো-আপের পর রোগীর আসা উত্তর AI রিভিউ করে",
  "Answer Patient Question": "রোগীর প্রশ্নের উত্তর দিন",
  "Answering...": "উত্তর তৈরি হচ্ছে...",
  "Bangla answer": "বাংলা উত্তর",
  "Bangla response": "বাংলা উত্তর",
  "Capture Bangla-English intake at reception.":
    "রিসেপশনে বাংলা-ইংরেজি ইনটেক নিন।",
  "Case summary": "কেস সারাংশ",
  "Chief complaint": "প্রধান অভিযোগ",
  "Clinic flow": "ক্লিনিক ফ্লো",
  "Clinic tracks follow-up and anonymized trends.":
    "ক্লিনিক ফলো-আপ ও অ্যানোনিমাইজড ট্রেন্ড ট্র্যাক করে।",
  Close: "বন্ধ করুন",
  "Clinician review": "ক্লিনিশিয়ান রিভিউ",
  "Clinician reviews and approves the note.":
    "ক্লিনিশিয়ান নোট রিভিউ ও অনুমোদন করেন।",
  "Command Copilot": "কমান্ড কোপাইলট",
  Concerning: "উদ্বেগজনক",
  Copy: "কপি",
  "Current case": "বর্তমান কেস",
  "Doctor Console": "ডাক্তার কনসোল",
  "Draft support only, clinician reviewed": "শুধু ড্রাফট সহায়তা, ক্লিনিশিয়ান রিভিউড",
  "English answer": "ইংরেজি উত্তর",
  "English response": "ইংরেজি উত্তর",
  "Load a scenario to start": "শুরু করতে একটি সিনারিও লোড করুন",
  "Missing Questions": "মিসিং প্রশ্ন",
  "Missing questions found": "মিসিং প্রশ্ন পাওয়া",
  "Paste a patient question, or ask the command box to answer it.":
    "রোগীর প্রশ্ন পেস্ট করুন, অথবা কমান্ড বক্সকে উত্তর দিতে বলুন।",
  "Paste a patient reply, or ask the command box to triage it.":
    "রোগীর উত্তর পেস্ট করুন, অথবা কমান্ড বক্সকে ট্রায়াজ করতে বলুন।",
  "Paste the patient or family question first.":
    "আগে রোগী বা পরিবারের প্রশ্ন পেস্ট করুন।",
  "Paste the patient's reply before triage.": "ট্রায়াজের আগে রোগীর উত্তর পেস্ট করুন।",
  "Patient Question": "রোগীর প্রশ্ন",
  "Patient follow-up reply": "রোগীর ফলো-আপ উত্তর",
  "Patient or family question": "রোগী বা পরিবারের প্রশ্ন",
  "Patient leaves with a plain Bangla handout.":
    "রোগী সহজ বাংলা হ্যান্ডআউট নিয়ে যায়।",
  "Patient question answer failed.": "রোগীর প্রশ্নের উত্তর তৈরি ব্যর্থ হয়েছে।",
  "Red flags caught": "রেড ফ্ল্যাগ ধরা",
  "Red flags": "রেড ফ্ল্যাগ",
  Reassuring: "আশ্বস্তকর",
  "Reply Triage": "রিপ্লাই ট্রায়াজ",
  "Reply triage failed.": "রিপ্লাই ট্রায়াজ ব্যর্থ হয়েছে।",
  "Safety Red Flags": "সেফটি রেড ফ্ল্যাগ",
  "Safety reminders": "সেফটি রিমাইন্ডার",
  "Save edits": "এডিট সেভ করুন",
  "Seeded demo cases": "সিডেড ডেমো কেস",
  "SOAP note": "SOAP নোট",
  "Staff actions": "স্টাফ অ্যাকশন",
  "Suggested commands": "সাজেস্টেড কমান্ড",
  Shortcuts: "শর্টকাট",
  "Teach-back": "টিচ-ব্যাক",
  "Triage Patient Reply": "রোগীর উত্তর ট্রায়াজ করুন",
  "Triaging...": "ট্রায়াজ হচ্ছে...",
  "Use the command copilot or guided workflow controls to drive the presentation.":
    "প্রেজেন্টেশন চালাতে কমান্ড কোপাইলট বা গাইডেড ওয়ার্কফ্লো কন্ট্রোল ব্যবহার করুন।",
  "AI finds missing questions and urgent red flags.":
    "AI মিসিং প্রশ্ন ও জরুরি রেড ফ্ল্যাগ খুঁজে।",
  "AI final packet, follow-up closure, and audit notes":
    "AI ফাইনাল প্যাকেট, ফলো-আপ ক্লোজার ও অডিট নোট",
  "AI parses lab, prescription, and OCR text into case facts":
    "AI ল্যাব, প্রেসক্রিপশন ও OCR টেক্সট থেকে কেস তথ্য বের করে",
  Admin: "অ্যাডমিন",
  "Admin workspace": "অ্যাডমিন ওয়ার্কস্পেস",
  "Apply addendum to intake": "ইনটেকে অ্যাডেনডাম যোগ করুন",
  "Attach or paste report text, then ask the command box to extract it.":
    "রিপোর্ট টেক্সট অ্যাটাচ বা পেস্ট করুন, তারপর কমান্ড বক্সকে এক্সট্র্যাক্ট করতে বলুন।",
  "Audit notes": "অডিট নোট",
  "Before patient leaves": "রোগী যাওয়ার আগে",
  Builder: "বিল্ডার",
  "Builder workspace": "বিল্ডার ওয়ার্কস্পেস",
  Case: "কেস",
  "Case workspace": "কেস ওয়ার্কস্পেস",
  "Chat, tools, runs, approvals, memory, MCP":
    "চ্যাট, টুল, রান, অ্যাপ্রুভাল, মেমরি, MCP",
  "Capture intake": "ইনটেক নিন",
  "Clean intake note with AI": "AI দিয়ে ইনটেক নোট পরিষ্কার করুন",
  "Close help drawer": "হেল্প ড্রয়ার বন্ধ করুন",
  "Close Visit Safely": "নিরাপদে ভিজিট ক্লোজ করুন",
  "Close workspace navigation": "ওয়ার্কস্পেস নেভিগেশন বন্ধ করুন",
  Closing: "ক্লোজ হচ্ছে",
  "Closing...": "ক্লোজ হচ্ছে...",
  "Copilot output is draft support only.": "কোপাইলট আউটপুট শুধু ড্রাফট সহায়তা।",
  "Copilot workspace": "কোপাইলট ওয়ার্কস্পেস",
  "Paste Bangla, English, or mixed notes.": "বাংলা, ইংরেজি বা মিশ্র নোট পেস্ট করুন।",
  "Document extraction failed.": "ডকুমেন্ট এক্সট্র্যাকশন ব্যর্থ হয়েছে।",
  "Document Extractor": "ডকুমেন্ট এক্সট্র্যাক্টর",
  "Extract Document Text": "ডকুমেন্ট টেক্সট এক্সট্র্যাক্ট করুন",
  Extracting: "এক্সট্র্যাক্ট হচ্ছে",
  "Extracting...": "এক্সট্র্যাক্ট হচ্ছে...",
  "Follow-up closure": "ফলো-আপ ক্লোজার",
  "Generate draft": "ড্রাফট তৈরি করুন",
  "AI extracts structure and safety gaps.": "AI কাঠামো ও সেফটি গ্যাপ বের করে।",
  "Generate or select a case before closing the visit.":
    "ভিজিট ক্লোজ করার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  Help: "হেল্প",
  "Help and tools": "হেল্প ও টুল",
  "MCP call failed.": "MCP কল ব্যর্থ হয়েছে।",
  "One patient, intake, safety, draft, packet":
    "এক রোগী, ইনটেক, সেফটি, ড্রাফট, প্যাকেট",
  "Open public docs and tool catalog": "পাবলিক ডকস ও টুল ক্যাটালগ খুলুন",
  "Open workspace navigation": "ওয়ার্কস্পেস নেভিগেশন খুলুন",
  "Operations workspace": "অপারেশনস ওয়ার্কস্পেস",
  "Paste or attach lab, prescription, or OCR text first.":
    "আগে ল্যাব, প্রেসক্রিপশন বা OCR টেক্সট পেস্ট বা অ্যাটাচ করুন।",
  "Prepare final staff steps, patient instructions, print packet, and audit notes before the visit leaves the workflow.":
    "ভিজিট ওয়ার্কফ্লো ছাড়ার আগে ফাইনাল স্টাফ স্টেপ, রোগীর নির্দেশনা, প্রিন্ট প্যাকেট ও অডিট নোট প্রস্তুত করুন।",
  "Primary mobile workspace": "প্রাইমারি মোবাইল ওয়ার্কস্পেস",
  "Print packet": "প্রিন্ট প্যাকেট",
  Queue: "কিউ",
  "Queue workspace": "কিউ ওয়ার্কস্পেস",
  "Review handout": "হ্যান্ডআউট রিভিউ করুন",
  "Doctor approves patient instructions.": "ডাক্তার রোগীর নির্দেশনা অনুমোদন করেন।",
  doctor: "ডাক্তার",
  nurse: "নার্স",
  receptionist: "রিসেপশনিস্ট",
  "Settings, roles, MCP, audit, readiness": "সেটিংস, রোল, MCP, অডিট, রেডিনেস",
  "Shift brief, analytics, follow-up, offline sync":
    "শিফট ব্রিফ, অ্যানালিটিক্স, ফলো-আপ, অফলাইন সিঙ্ক",
  "Shortcuts, safety rules, and tool reference live here so the workspace can stay calm.":
    "শর্টকাট, সেফটি রুল ও টুল রেফারেন্স এখানে থাকে, যাতে ওয়ার্কস্পেস শান্ত থাকে।",
  "Sign out": "সাইন আউট",
  "Staff closeout": "স্টাফ ক্লোজআউট",
  "Use Case for patient work; use Copilot for questions and agent actions.":
    "রোগীর কাজের জন্য Case ব্যবহার করুন; প্রশ্ন ও এজেন্ট অ্যাকশনের জন্য Copilot ব্যবহার করুন।",
  "Useful Copilot asks": "ব্যবহারযোগ্য কোপাইলট প্রশ্ন",
  "Visit Closeout": "ভিজিট ক্লোজআউট",
  "Visit closeout failed.": "ভিজিট ক্লোজআউট ব্যর্থ হয়েছে।",
  "Vitals, allergies, escalation, return warnings, and clinician approval stay visible before print.":
    "প্রিন্টের আগে ভাইটাল, অ্যালার্জি, এসক্যালেশন, রিটার্ন ওয়ার্নিং ও ক্লিনিশিয়ান অনুমোদন দৃশ্যমান থাকে।",
  "Waiting room, red flags, owners, and follow-ups":
    "ওয়েটিং রুম, রেড ফ্ল্যাগ, মালিকানা ও ফলো-আপ",
  "Workflow canvas, protocols, simulation, templates":
    "ওয়ার্কফ্লো ক্যানভাস, প্রোটোকল, সিমুলেশন, টেমপ্লেট",
  Workspace: "ওয়ার্কস্পেস",
  workspace: "ওয়ার্কস্পেস",
  "Cmd/Ctrl+G generates a draft": "Cmd/Ctrl+G ড্রাফট তৈরি করে",
  "Cmd/Ctrl+K opens Copilot": "Cmd/Ctrl+K কোপাইলট খোলে",
  "Cmd/Ctrl+P opens presentation mode": "Cmd/Ctrl+P প্রেজেন্টেশন মোড খোলে",
  "Esc closes presentation mode": "Esc প্রেজেন্টেশন মোড বন্ধ করে",
  "Explain this in simple Bangla.": "এটা সহজ বাংলায় ব্যাখ্যা করুন।",
  "Is this safe to print?": "এটা প্রিন্ট করা নিরাপদ কি?",
  "Prepare follow-up ownership.": "ফলো-আপ মালিকানা প্রস্তুত করুন।",
  "What should I do next?": "এরপর কী করা উচিত?",
  bn: "বাংলা",
  en: "ইংরেজি",
  h: "ঘণ্টা",
  m: "মিনিট",
  mixed: "মিশ্র",
  "AI checks blockers before clinician signoff":
    "ক্লিনিশিয়ান সাইনঅফের আগে AI ব্লকার চেক করে",
  "AI task split for receptionist, nurse, doctor, and follow-up desk":
    "রিসেপশনিস্ট, নার্স, ডাক্তার ও ফলো-আপ ডেস্কের জন্য AI টাস্ক ভাগ করে",
  "Approval Guard": "অ্যাপ্রুভাল গার্ড",
  "Approval readiness check failed.": "অ্যাপ্রুভাল রেডিনেস চেক ব্যর্থ হয়েছে।",
  "Accessibility notes": "অ্যাক্সেসিবিলিটি নোট",
  "AI callback timing, reminders, and closure rules":
    "AI কলব্যাক টাইমিং, রিমাইন্ডার ও ক্লোজার রুল",
  "AI turns the selected case into actions and commands":
    "AI সিলেক্ট করা কেসকে অ্যাকশন ও কমান্ডে বদলায়",
  "Ask for a nurse handoff or team task list from the command box.":
    "কমান্ড বক্স থেকে নার্স হ্যান্ডঅফ বা টিম টাস্ক লিস্ট চাইুন।",
  "Ask why a case is risky, or run the explanation here.":
    "কেসটি কেন ঝুঁকিপূর্ণ তা জিজ্ঞেস করুন, অথবা এখানে ব্যাখ্যা চালান।",
  Blockers: "ব্লকার",
  "Check Approval Readiness": "অ্যাপ্রুভাল রেডিনেস চেক করুন",
  "Check whether the selected draft is ready for clinician approval.":
    "সিলেক্ট করা ড্রাফট ক্লিনিশিয়ান অনুমোদনের জন্য প্রস্তুত কিনা চেক করুন।",
  "Checking...": "চেক হচ্ছে...",
  "Clinician actions": "ক্লিনিশিয়ান অ্যাকশন",
  "Copy handoff": "হ্যান্ডঅফ কপি করুন",
  "Copy rationale": "রেশনাল কপি করুন",
  "Create Staff Handoff": "স্টাফ হ্যান্ডঅফ তৈরি করুন",
  "Creating handoff...": "হ্যান্ডঅফ তৈরি হচ্ছে...",
  Doctor: "ডাক্তার",
  "Evidence against risk": "ঝুঁকির বিপরীত প্রমাণ",
  "Evidence for risk": "ঝুঁকির পক্ষে প্রমাণ",
  "Close when": "ক্লোজ করুন যখন",
  "Do next": "এরপর করুন",
  "Escalate if": "এসক্যালেট করুন যদি",
  "Explain Risk": "ঝুঁকি ব্যাখ্যা করুন",
  "Explainable safety reasoning for review":
    "রিভিউয়ের জন্য ব্যাখ্যাযোগ্য সেফটি রিজনিং",
  "Explaining...": "ব্যাখ্যা হচ্ছে...",
  "Follow-up desk": "ফলো-আপ ডেস্ক",
  "Follow-up Scheduler": "ফলো-আপ শিডিউলার",
  "Follow-up scheduling failed.": "ফলো-আপ শিডিউলিং ব্যর্থ হয়েছে।",
  "Generate or select a case before creating a handoff.":
    "হ্যান্ডঅফ তৈরির আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a case before planning next steps.":
    "পরবর্তী ধাপ প্ল্যান করার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a case before scheduling follow-up.":
    "ফলো-আপ শিডিউল করার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a case before explaining risk.":
    "ঝুঁকি ব্যাখ্যার আগে একটি কেস তৈরি বা সিলেক্ট করুন।",
  "Generate or select a draft before checking approval.":
    "অ্যাপ্রুভাল চেক করার আগে একটি ড্রাফট তৈরি বা সিলেক্ট করুন।",
  "Handoff script": "হ্যান্ডঅফ স্ক্রিপ্ট",
  "Next-Step Navigator": "নেক্সট-স্টেপ নেভিগেটর",
  "Next-step planning failed.": "নেক্সট-স্টেপ প্ল্যানিং ব্যর্থ হয়েছে।",
  Owner: "মালিকানা",
  "Patient communication": "রোগীর যোগাযোগ",
  "Plan Next Steps": "পরবর্তী ধাপ প্ল্যান করুন",
  "Planning...": "প্ল্যান হচ্ছে...",
  "Missing checks": "মিসিং চেক",
  Nurse: "নার্স",
  "Patient safety net": "রোগীর সেফটি নেট",
  "Ready signals": "রেডি সিগনাল",
  Receptionist: "রিসেপশনিস্ট",
  "Risk explanation failed.": "ঝুঁকি ব্যাখ্যা ব্যর্থ হয়েছে।",
  "Risk level": "ঝুঁকির স্তর",
  "Risk Rationale": "ঝুঁকির রেশনাল",
  Reminders: "রিমাইন্ডার",
  "Schedule Follow-up": "ফলো-আপ শিডিউল করুন",
  "Schedule callback timing and escalation rules after a draft is ready.":
    "ড্রাফট প্রস্তুত হওয়ার পর কলব্যাক টাইমিং ও এসক্যালেশন রুল শিডিউল করুন।",
  "Scheduling...": "শিডিউল হচ্ছে...",
  "Safety notes": "সেফটি নোট",
  "Signoff checklist": "সাইনঅফ চেকলিস্ট",
  "Staff handoff failed.": "স্টাফ হ্যান্ডঅফ ব্যর্থ হয়েছে।",
  "Staff Handoff": "স্টাফ হ্যান্ডঅফ",
  Uncertainty: "অনিশ্চয়তা",
  Urgency: "জরুরিতা",
  "Ask what to do next and the app will suggest safe workflow commands.":
    "এরপর কী করতে হবে জিজ্ঞেস করুন, অ্যাপ নিরাপদ ওয়ার্কফ্লো কমান্ড সাজেস্ট করবে।",
  "AI queue summary for the next safe move":
    "পরবর্তী নিরাপদ মুভের জন্য AI কিউ সারাংশ",
  "Ask Command Copilot to brief the clinic, or run it here.":
    "কমান্ড কোপাইলটকে ক্লিনিক ব্রিফ করতে বলুন, অথবা এখানে চালান।",
  "Brief Clinic Queue": "ক্লিনিক কিউ ব্রিফ করুন",
  "Briefing...": "ব্রিফিং হচ্ছে...",
  "Check medicine safety": "ওষুধের সেফটি চেক করুন",
  "Checks clarity, allergies, and warning language":
    "ক্ল্যারিটি, অ্যালার্জি ও সতর্কতার ভাষা চেক করে",
  "Clarifying questions": "ক্ল্যারিফাইং প্রশ্ন",
  "Clinic Briefing": "ক্লিনিক ব্রিফিং",
  "Clinic briefing failed.": "ক্লিনিক ব্রিফিং ব্যর্থ হয়েছে।",
  "Copy briefing": "ব্রিফিং কপি করুন",
  "Copy handout": "হ্যান্ডআউট কপি করুন",
  Care: "যত্ন",
  "Draft medicine instructions": "ড্রাফট ওষুধ নির্দেশনা",
  "Follow-up actions": "ফলো-আপ অ্যাকশন",
  Issues: "ইস্যু",
  "Medicine check failed.": "ওষুধ চেক ব্যর্থ হয়েছে।",
  Medicine: "ওষুধ",
  "Medicine Safety": "ওষুধ সেফটি",
  "Next best actions": "নেক্সট বেস্ট অ্যাকশন",
  "Paperwork gaps": "পেপারওয়ার্ক গ্যাপ",
  Paperwork: "পেপারওয়ার্ক",
  "Patient instructions": "রোগীর নির্দেশনা",
  "Print handout": "হ্যান্ডআউট প্রিন্ট করুন",
  "Generate a draft to create a shareable handout.":
    "শেয়ার করা যায় এমন হ্যান্ডআউট তৈরি করতে একটি ড্রাফট জেনারেট করুন।",
  "Urgent return": "জরুরি ফেরত আসা",
  "Priority patients": "অগ্রাধিকার রোগী",
  risk: "ঝুঁকি",
  Approve: "অনুমোদন করুন",
  approved: "অনুমোদিত",
  "Convex realtime queue": "Convex রিয়েলটাইম কিউ",
  "Filter by severity": "সিভিয়ারিটি দিয়ে ফিল্টার করুন",
  "Filter by status": "স্ট্যাটাস দিয়ে ফিল্টার করুন",
  flags: "ফ্ল্যাগ",
  "Follow-up": "ফলো-আপ",
  followup: "ফলো-আপ",
  "Follow-up clock": "ফলো-আপ ঘড়ি",
  "Generated cases will appear here.": "জেনারেট করা কেস এখানে দেখা যাবে।",
  Handout: "হ্যান্ডআউট",
  handout: "হ্যান্ডআউট",
  "just arrived": "এখনই এসেছে",
  "Live Case Board": "লাইভ কেস বোর্ড",
  "Move to follow-up": "ফলো-আপে নিন",
  "Move to handout": "হ্যান্ডআউটে নিন",
  "Open urgent case": "জরুরি কেস খুলুন",
  "owner: doctor": "মালিকানা: ডাক্তার",
  "owner: follow-up desk": "মালিকানা: ফলো-আপ ডেস্ক",
  "owner: nurse": "মালিকানা: নার্স",
  "owner: reception": "মালিকানা: রিসেপশন",
  "Patient, complaint, language...": "রোগী, অভিযোগ, ভাষা...",
  priority: "অগ্রাধিকার",
  "Red Flag Lane": "রেড ফ্ল্যাগ লেন",
  "red flag lane": "রেড ফ্ল্যাগ লেন",
  review: "রিভিউ",
  "routine lane": "রুটিন লেন",
  "Search cases": "কেস খুঁজুন",
  "Select case": "কেস সিলেক্ট করুন",
  status: "স্ট্যাটাস",
  "timing not set": "টাইমিং সেট করা নেই",
  waiting: "অপেক্ষমাণ",
  yrs: "বছর",
  all: "সব",
  confidence: "কনফিডেন্স",
  high: "উচ্চ",
  "high priority": "উচ্চ অগ্রাধিকার",
  blocked: "ব্লকড",
  Clarify: "ক্ল্যারিফাই",
  Labs: "ল্যাব",
  low: "নিম্ন",
  "low priority": "নিম্ন অগ্রাধিকার",
  Medicines: "ওষুধ",
  medium: "মাঝারি",
  "medium priority": "মাঝারি অগ্রাধিকার",
  ready: "রেডি",
  "Safety issues": "সেফটি ইস্যু",
  urgent: "জরুরি",
  Vitals: "ভাইটাল",
};

export function useClinicText() {
  const { language } = useLanguage();
  return useCallback(
    (text: string) => (language === "bn" ? (clinicTextBn[text] ?? text) : text),
    [language],
  );
}
